### ISSUE TITLE
Not able to download charts when deploying solution

### ISSUE THREAD

**Issue by tobiaschielens** [threefoldtech/vdc-solutions-charts#1]
Setup an environment locally and on https://www.oreilly.com/katacoda/for-lead-gen.html

Repro steps:
Installed kubectl kind and minicube
https://kubernetes.io/docs/tasks/tools/
started up cluster with either minicube or kind

Installed helm:
https://helm.sh/docs/intro/install/
helm repo add marketplace https://threefoldtech.github.io/vdc-solutions-charts
helm repo update

``` 
helm install mattermost marketplace/mattermost \
   --set mysql.mysqlUser=userName \
   --set mysql.mysqlPassword="userPassword" \
   --set mysql.mysqlRootPassword="userPassword" \
   --set ingress.host="example.yourdomain.com"
 ```

![image](https://user-images.githubusercontent.com/17977313/100989080-b8433480-3550-11eb-8f76-1e6633f460d2.png)

**Comment by ashraffouda** [comment]
this is because the repo name has changed 
when I tried it I had the same issue 
![Screenshot from 2020-12-03 12-05-22](https://user-images.githubusercontent.com/1689456/100995005-e1b78c80-355f-11eb-9562-2d5d43a57734.png)
doing `helm repo update` didn't help
![Screenshot from 2020-12-03 12-03-29](https://user-images.githubusercontent.com/1689456/100994881-bfbe0a00-355f-11eb-8b3d-39d2b27fe70f.png)
consider removing the repo 
`helm repo remove marketplace`
then add it again 
`helm repo add marketplace https://threefoldtech.github.io/vdc-solutions-charts/`
`helm repo update`
`helm search repo mattermost`
![Screenshot from 2020-12-03 12-09-22](https://user-images.githubusercontent.com/1689456/100995432-6efae100-3560-11eb-9f65-25fd69384815.png)

**Comment by tobiaschielens** [comment]
As seen in the helm repo list command this has already happend
![image](https://user-images.githubusercontent.com/17977313/100996044-e593e080-3558-11eb-8fb9-babd52a3bc0c.png)

Also on the clean machine it is not working

**Comment by ashraffouda** [comment]
seems working with me 
![Screenshot from 2020-12-03 12-30-03](https://user-images.githubusercontent.com/1689456/100997772-6061f900-3563-11eb-812e-20655d5af406.png)

**Comment by ashraffouda** [comment]
even on katacoda
![Screenshot from 2020-12-03 12-56-53 (copy)](https://user-images.githubusercontent.com/1689456/101001061-52ae7280-3567-11eb-86f0-285767253bcc.png)
![Screenshot from 2020-12-03 12-57-51 (copy)](https://user-images.githubusercontent.com/1689456/101001067-54783600-3567-11eb-8de4-c6cd2032cdc0.png)

**Comment by tobiaschielens** [comment]
Please update the wiki here: https://threefoldtech.github.io/vdc-solutions-charts/

There is a typo in `helm install markteplace/<chart-name>`
please update markteplace to marketplace

**Comment by xmonader** [comment]
> Please update the wiki here: https://threefoldtech.github.io/vdc-solutions-charts/
> 
> There is a typo in `helm install markteplace/<chart-name>`
> please update markteplace to marketplace

I updated, does this means it's ok for you now?

**Comment by tobiaschielens** [comment]
Now it is working yeah. Overlooked that this typo was there.
