### ISSUE TITLE
Deployment of Matic sentry node fails

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/vdc-solutions-charts#121]
I tried to deploy a Matic sentry node on a new diamond VDC. It failed with 'alert ID' 2. No idea what it means. Also tried it on another, previously existing VDC that I upgraded to get enough hard drive space. Same result, alert ID 2.

VDC: vdcdiamondtest
![image](https://user-images.githubusercontent.com/30384423/111490733-8dfe3700-873b-11eb-9bfc-a873d2151f31.png)

**Comment by abdulgig** [comment]
@gmachtel , please test again and let us know

**Comment by siddiquagig** [comment]
Just deployed a matic node and tested both on silver and gold packages.

https://masid-matic-polymatic9.webg1test.grid.tf/

**Comment by gmachtel** [comment]
Tried to test it out, but now blocked due to another issue: https://github.com/threefoldtech/vdc-solutions-charts/issues/124

**Comment by abdulgig** [comment]
https://github.com/threefoldtech/vdc-solutions-charts/issues/124 may be due to previous deployments of matic that got actually deployed but were not listed. That was fixed with PR https://github.com/threefoldtech/js-sdk/pull/2771 yesterday.

So you can create a new VDC and then test. For existing vdc, you will need to uninstall old deployments.

You could see them with ```helm ls --all-namespaces```, and then delete them. If you don't,  you will get the error https://github.com/threefoldtech/vdc-solutions-charts/issues/124 which is valid

**Comment by gmachtel** [comment]
OK
