### ISSUE TITLE
presearch pods are restarting

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/vdc-solutions-charts#148]
There are 2 vdcs with running pre-search that are keeps restarting

![image](https://user-images.githubusercontent.com/10658229/127129037-8296d9c1-9a23-4b88-a12a-2f3c44beacf0.png)
![Screenshot from 2021-07-27 11-16-01](https://user-images.githubusercontent.com/10658229/127129095-cd20c436-cc94-480d-8b2d-7ad45d4b9222.png)

**Comment by abdulgig** [comment]
@waleedhammam , this was on purpose to have the pod restart once a day so that if there is a new version of the image, it will pull and upgrade automatically without having the user to do himself. 

Reference to the discussion in this ticket , https://github.com/threefoldtech/js-sdk/issues/2626

At that time, the Presearch API wasn't released to make it event driven. We will investigate and evaluate if this can be handled differently

**Comment by scottyeager** [comment]
@abdulgig, updates were always handled automatically by having the proper Kubernetes pull policy along with the fact that Presearch uses a signaling mechanism to kill containers when an update is required. I tried to explain this, at great length, in the sdk issue you mentioned.

The only reason to restart the pods was the zombie issue also mentioned in that issue. We settled on providing the user a restart button to take care of this themselves. Therefore, I'm rather confused about why a daily restart was included in these deployments, especially without consideration for the strain it would place on our SSL service.

**Comment by abdulgig** [comment]
@scottyeager We wanted to go the extra mile and ensure that the users always had the updated version of the node without even having them doing anything manually. However, the SSL certificate issuance got overlooked! We have already disabled any auto restarts for any upcoming deployments.
